### ISSUE TITLE
[Feature Request] Pass refundTimespan to constructor instead of refundEndTime_

### ISSUE THREAD

**Issue by ramyhhh** [ERC721RA/erc721ra#12]
Currently the contract constructor is accepting the time in which the refund is expected to expire, however this is tricky to calculate during deployment also it would mean different constructor parameters for each network even for test nets. I suggest passing the time span instead ex: 1 days.

```solidity
constructor(
        string memory name_,
        string memory symbol_,
        uint256 refundTimespan_
    ) {
        _name = name_;
        _symbol = symbol_;

        _refundEndTime = block.timestamp + refundTimespan_;
        _returnAddress = _msgSender();

        _currentIndex = _startTokenId();
   }
```

**Comment by 0xwil** [comment]
Hey Rami, thanks for your suggestion.

The trade off of passing the timespan is you have to calculate the (block.timestamp + timespan) when you deploy the contract, which does add up the gas.

However child contract can calculate the `_refundEndTime = block.timestamp + refundTimespan_` and pass the `_refundEndTime` to the constructor of the parent contract.

**Comment by ramyhhh** [comment]
For reference I've tried deploying the contract and here are the gas results. For passing the `_refundEndTime` directly it's `2645251` while passing `block.timestamp + refundTimespan_` costed `2650744` so the difference is `5493` which is not that significant, however you are totally right the child contract can simply pass the end time dynamically like:

```solidity
contract My721raToken is ERC721RA {   
    constructor() ERC721RA("NAME", "SYM",block.timestamp +(14 days)) { }
}
```
